easy_admin:
    site_name: You Library Administration

    design:
        menu:
            - { route: 'home', label: 'Back to website', icon: 'home' }
            - { entity: 'Editor', label: 'Editor', icon: 'newspaper' }

    entities:
        - App\Entity\Editor
#        - App\Entity\Category
#        - App\Entity\User
